### ISSUE TITLE
#error - image from 2013

### ISSUE THREAD

**Issue by llunymanu** [spanishpolice/spanishpolice.github.io#1]
Hola,
Des de la xarxa d'entitats #SomDefensores creiem identificar que la imatge que ilustra el video "Catalonia Referendum - Firefighters sacrifice themselves as human shields to protect people" és de 2013, no de l'1 Octubre 2017. Sugerim que es canvii per tal de no perjudicar la credibilitat de la pàgina.

**Comment by albertfdp** [comment]
També la imatge que il.lustra el vídeo "Catalan Referendum - Brutal attack police protesters LIVE" no es correspon, de fet no sembla policia de l'Estat tampoc.

**Comment by spanishpolice** [comment]
Thanks by your help.
